### ISSUE TITLE
undefined name 'self'

### ISSUE THREAD

**Issue by rerowep** [inveniosoftware/invenio-circulation#58]
https://github.com/inveniosoftware/invenio-circulation/blob/02e3a67a3bf491c0a180dae7a52b86d8cd37dc57/invenio_circulation/transitions/transitions.py#L49

Should it be `loan` instead?

**Comment by ntarocco** [comment]
`self.dest` is correct, it is the name of the destination state (next state) performed by the transition.
It should not be undefined.
@rerowep what do you mean exactly with `undefined`? Did you have an error?

**Comment by zzacharo** [comment]
This issue is outdated as it has already been fixed here https://github.com/inveniosoftware/invenio-circulation/blob/master/invenio_circulation/transitions/base.py#L104
