### ISSUE TITLE
views missing config for `CIRCULATION_LOAN_LINKS_FACTORY `

### ISSUE THREAD

**Issue by zzacharo** [inveniosoftware/invenio-circulation#74]
Here https://github.com/inveniosoftware/invenio-circulation/blob/master/invenio_circulation/views.py#L90 the loan links factory is retrieved from the config `CIRCULATION_LOAN_LINKS_FACTORY ` but is never set to a default. Also should be changed to be able to be overridden  by an external module like `invenio-app-ils`.

**Comment by kpsherva** [comment]
bug reintroduced in https://github.com/inveniosoftware/invenio-circulation/pull/82/files

**Comment by zzacharo** [comment]
The bug has been fixed in https://github.com/inveniosoftware/invenio-circulation/commit/8349241adedcc9e1e0b926fa8b355d62b38d73a4

**Comment by zzacharo** [comment]
#84 completes this issue by making `loan_links_factory` extendable from external module.
